{% set name = "mp_time_split" %}
{% set version = "0.1.4" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mp-time-split-{{ version }}.tar.gz
  sha256: b31db1ab7781a2c7fc74cec335a8ce87b85bce2a4a7d88fd8a9804d4275d719f

build:
  number: {{ build_num }}

outputs:
  - name: {{ name }}
    build:
      entry_points:
        - mp_time_split = mp_time_split.core:run
      number: 0
      noarch: python
    script: build_base.sh

    requirements:
      host:
        - pip
        - setuptools-scm
        - python >=3.6
      run:
        - matminer
        - pymatgen
        - scikit-learn
        - pybtex
        - python >=3.6
        - importlib-metadata
    test:
      imports:
        - mp_time_split
      commands:
        - pip check
        - mp_time_split --help
      requires:
        - pip

  - name: {{ name.replace("_", "-") }}
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - mp_time_split

about:
  home: https://github.com/sparks-baird/mp-time-split
  summary: Use Materials Project time-splits for generative modeling benchmarking.
  dev_url: https://github.com/sparks-baird/mp-time-split
  license: MIT
  license_file: LICENSE.txt
  doc_url: mp-time-split.readthedocs.io

extra:
  recipe-maintainers:
    - sgbaird
